services:
  app:
    build: .
    image: radiko_timeshift_recorder:latest
    pull_policy: build
    user: "1000:1000"
    volumes:
      - type: bind
        source: /etc/passwd
        target: /etc/passwd
        read_only: true
      - type: bind
        source: /etc/group
        target: /etc/group
        read_only: true
      - type: bind
        source: ./out
        target: /radiko_timeshift_recorder/out
        read_only: false
      - type: bind
        source: ./rules
        target: /radiko_timeshift_recorder/rules
        read_only: true
    command: ["run-server", "--out-dir", "out"]
