services:
  app:
    build: .
    image: radiko_timeshift_recorder:latest
    pull_policy: build
    env_file:
      - ./.env
    volumes:
      - ./out:/radiko_timeshift_recorder/out
      - ./rules:/radiko_timeshift_recorder/rules
