name: Generate JSON Schema

on:
  release:
    types: [created]

permissions:
  contents: write

jobs:
  generate-and-upload-schema:
    name: Generate and Upload Rules JSON Schema
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.12.0"
          cache: "pipenv"

      - name: Install pipenv
        run: pip install pipenv

      - name: Install dependencies
        run: pipenv sync --dev

      - name: Generate JSON Schema for Rules
        id: generate_schema
        run: pipenv run python -m radiko_timeshift_recorder gen-json-schema-for-rules > rules.schema.json

      - name: Upload JSON Schema to Release
        env:
          GH_TOKEN: ${{ github.token }}
        run: gh release upload ${{ github.event.release.tag_name }} rules.schema.json --clobber
